opam-version: "1"
version: "4.00.1"
src: "http://caml.inria.fr/pub/distrib/ocaml-4.00/ocaml-4.00.1.tar.gz"
patches: ["https://github.com/cgreenhalgh/ocaml/commit/f617a0fb82421e3da2f7ea849b5d83c3a3c416fa.patch"]
build: [
  ["./configure" "-prefix" "%{prefix}%"]
  ["%{make}%" "world"]
  ["%{make}%" "world.opt"]
  ["%{make}%" "install"]
]
packages: ["base-unix" "base-threads" "base-bigarray" ]
env: [
  [MIRAGE_OS = "unix"]
  [MIRAGE_NET = "direct"]
]
